// CHECK FORMULAR
    // CHECK IF FIELD IS NOT EMPTY
        // ADD A NEW TASK
        // DISPLAY TASK LIST

// DISPLAY TASK LIST
    // FOR EVERY TASK OBJECT, CHECK EDIT MODE
    // CLEAR TASK LIST
    // ASSIGN NEW TASK LIST
    // FOCUS ON THE INPUT

// CREATE A NEW TASK
    // CLEATE LIST TAG
    // CREATE BUTTON DELETE
    // ADD EVENT TO BUTTON DELETE
    // CREATE BUTTON EDIT
    // ADD EVENT TO BUTTON EDIT
    // ADD LABEL TO TASK AND CHECK IF TASK IS DONE
    // ADD EVENT ON LI TAG TO TOGGLE DONE TASK
    // ADD BUTTON TO LIST TAG

// EDIT TASK
    // CREATE LIST TAG
    // CREATE INPUT
    // CREATE BUTTON SAVE
    // ADD EVENT TO BUTTON SAVE
    // CREATE BUTTON CANCEL
    // ADD EVENT TO BUTTON CANCEL
    // ADD BUTTON TO LIST TAG

// ADD TASK PROPERTY
// DELETE TASK PROPERTY
// TOGGLE DONE TASK
// TOGGLE EDIT MODE
// EDIT TASK PROPERTY

// DISPLAY TODO LIST BY DEFAULT